apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alex-alvesb/kubernetes-multicloud.git
    targetRevision: main
    path: azure-aks/k8s/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true