apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: 679346886253.dkr.ecr.us-east-1.amazonaws.com/kubernetes-multicloud-sample-app:1e2de9ad6808da7bdb0f20f83375f7232d17bc71
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: dev
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80