apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: acrkubmulticloud4dc010b6.azurecr.io/kubernetes-multicloud-sample-app:d9134c8d02a3445bec367a2b1a9283c04cf1eff2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: dev
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80